// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2bVjVR9zHhwbBj2DB3V-xQINAqg2IzWQ',
    appId: '1:942626013305:web:fab67fae05734eba6cd4a8',
    messagingSenderId: '942626013305',
    projectId: 'costgo-commerce-app',
    authDomain: 'costgo-commerce-app.firebaseapp.com',
    storageBucket: 'costgo-commerce-app.firebasestorage.app',
    measurementId: 'G-76PZRLFDZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZFXexLQxmSAL4Bb81EHsZXOc5q4sW60',
    appId: '1:942626013305:android:83558652a695e38e6cd4a8',
    messagingSenderId: '942626013305',
    projectId: 'costgo-commerce-app',
    storageBucket: 'costgo-commerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQYaX4_Mq0U-rtj-Y0dSLjxG8AFfHFQJA',
    appId: '1:942626013305:ios:55f17d2b278359386cd4a8',
    messagingSenderId: '942626013305',
    projectId: 'costgo-commerce-app',
    storageBucket: 'costgo-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.costgoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQYaX4_Mq0U-rtj-Y0dSLjxG8AFfHFQJA',
    appId: '1:942626013305:ios:55f17d2b278359386cd4a8',
    messagingSenderId: '942626013305',
    projectId: 'costgo-commerce-app',
    storageBucket: 'costgo-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.costgoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2bVjVR9zHhwbBj2DB3V-xQINAqg2IzWQ',
    appId: '1:942626013305:web:90dd8daab8ce73a06cd4a8',
    messagingSenderId: '942626013305',
    projectId: 'costgo-commerce-app',
    authDomain: 'costgo-commerce-app.firebaseapp.com',
    storageBucket: 'costgo-commerce-app.firebasestorage.app',
    measurementId: 'G-1PBJYCX8G8',
  );
}
